=== LAPESI-IFPI/Opala/campos.dtd
<!ELEMENT DOCUMENT (ID, AUTHOR, TITLE, PUBLICATION-DATE,FORMAT?, TYPE?, KEYWORDS?,  FIELD*)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT PUBLICATION-DATE (#PCDATA)>
<!ELEMENT FORMAT (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT KEYWORDS (#PCDATA)>
<!ELEMENT FIELD (#PCDATA)>

<!ATTLIST FIELD NAME CDATA #REQUIRED>

=== LAPESI-IFPI/Opala/WebContent/resources/xml/teste_vazio.xml
<?xml version="1.0"?>
<!DOCTYPE DOCUMENT SYSTEM "campos.dtd">
<DOCUMENT>

	<ID></ID>
	
	<AUTHOR>
	</AUTHOR>

	<TITLE>
	</TITLE>
	
	<PUBLICATION-DATE>	</PUBLICATION-DATE>
	
	<FORMAT>
	</FORMAT>

    <TYPE>
    </TYPE>
    
    <KEYWORDS>
    </KEYWORDS>
    
    <FIELD NAME="tcharam">
   	</FIELD>
   	
   	<FIELD NAME="oia">
   	</FIELD>

</DOCUMENT>

=== LAPESI-IFPI/Opala/WebContent/resources/xml/teste.xml
<?xml version="1.0"?>
<!DOCTYPE DOCUMENT SYSTEM "campos.dtd">
<DOCUMENT>

	<ID>
	testeXMLDannylvan
	</ID>
	
	<AUTHOR>
	Dannylvan
	</AUTHOR>

	<TITLE>
	As Aventuras de Pequennylvan
	</TITLE>
	
	<PUBLICATION-DATE>
	02/02/2008
	</PUBLICATION-DATE>
	
	<FORMAT>
	txt
	</FORMAT>

    <TYPE>
    monografia
    </TYPE>
    
    <KEYWORDS>
    dannylvan xml metadados teste
    </KEYWORDS>
    
    <FIELD NAME="tcharam">
    	tcharamram!
   	</FIELD>
   	
   	<FIELD NAME="oia">
    	oiou!
   	</FIELD>

</DOCUMENT>
